### ISSUE TITLE
Export Order with discountCodes not working

### ISSUE THREAD

**Issue by esoliani** [sphereio/sphere-order-export#51]
### Description
When I try to export the order with discount code to a CSV file using the 'discountCodes' field in the CVS template

### Expected Behavior
I want to see the list of code used on the order

### Current Behavior
I get the following error:
```
{ data: {}, project_key: 'trw-prod' } 'Exporting orders as stream.'
.{ data: 
   { message: 'Cannot read property \'code\' of undefined',
     name: 'TypeError',
     stack: 'TypeError: Cannot read property \'code\' of undefined\n    at /app/node_modules/sphere-order-export/lib/mapping-utils/csv.js:119:34\n    at Function._.map._.collect (/app/node_modules/underscore/underscore.js:172:24)\n    at formatDiscountCodes (/app/node_modules/sphere-order-export/lib/mapping-utils/csv.js:117:14)\n    at CsvMapping._getValue (/app/node_modules/sphere-order-export/lib/mapping-utils/csv.js:70:25)\n    at /app/node_modules/sphere-order-export/lib/mapping-utils/csv.js:42:22\n    at Function._.map._.collect (/app/node_modules/underscore/underscore.js:172:24)\n    at CsvMapping._mapOrder (/app/node_modules/sphere-order-export/lib/mapping-utils/csv.js:40:17)\n    at /app/node_modules/sphere-order-export/lib/orderexport.js:132:39\n    at Function._.map._.collect (/app/node_modules/underscore/underscore.js:172:24)\n    at _this.client.orders.expand.expand.expand.expand.perPage.process.accumulate (/app/node_modules/sphere-order-export/lib/orderexport.js:131:22)\n    at /app/node_modules/sphere-order-export/node_modules/sphere-node-sdk/lib/services/base.js:268:20\n    at tryCatcher (/app/node_modules/sphere-order-export/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/sphere-order-export/node_modules/bluebird/js/main/promise.js:489:31)\n    at Promise._settlePromiseAt (/app/node_modules/sphere-order-export/node_modules/bluebird/js/main/promise.js:565:18)\n    at Promise._settlePromises (/app/node_modules/sphere-order-export/node_modules/bluebird/js/main/promise.js:681:14)\n    at Async._drainQueue (/app/node_modules/sphere-order-export/node_modules/bluebird/js/main/async.js:123:16)\n    at Async._drainQueues (/app/node_modules/sphere-order-export/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/sphere-order-export/node_modules/bluebird/js/main/async.js:15:14)\n    at processImmediate [as _immediateCallback] (timers.js:396:17)',
     code: undefined,
     signal: undefined },
  project_key: 'trw-prod' } 'Oops, something went wrong!'
```

### Context
I need to export the orders with promotion code. It seems that the order needs to be expanded with discountCodes[*].discountCode but this is not possible from the web

**Comment by junajan** [comment]
Hello @esoliani @VasumathiJayakumar .. do we have more info about this issue?

I tried to export discountCodes using this template `id,orderNumber,discountCodes` from a project which have some orders with discountCodes and it worked well:
```csv
id,orderNumber,discountCodes
58e5a292-92a3-4105-8335-7e5decdc446b,816366,newsletter
```

**Comment by Oehmi** [comment]
@VasumathiJayakumar @junajan I will close this ticket, the respective support ticket has been closed and the testing showed a working result. Thanks Jan.
